# 定义 Workflow 的名字
name: 同步更新blog

# 定义 Workflow 的触发器；合并主分支后，执行打包
on:
  push:
    branches: [ "master" ]

# 定义 Workflow 的 job
jobs:
  build:
    name: deploy to shenshuai89.github.io
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install node
        uses: actions/setup-node@v3.0.0
        with:
          node-version: "16.17.0"
          registry-url: https://registry.npmjs.org
      - name: 全局安装依赖
        run: npm install
      - name: build打包构建
        run: npm run build
      # - name: Deploy to Server
      #   uses: JamesIves/github-pages-deploy-action@releases/v3
      #   with:
      #     ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      #     REPOSITORY_NAME: shenshuai89/shenshuai89.github.io
      #     BRANCH: master
      #     FOLDER: docs/.vuepress/dist
      - name: Deploy Github Pages
        # You may pin to the exact commit or the version.
        # uses: ptienchuan/deploy-github-pages-action@abff2ab6d0300d579780d56bd3e70254c5b15403
        uses: Daniele-Tentoni/simple-github-pages-deployment@v1.0.1
        with:
          # Your Username or Organization name
          username: shenshuai89
          # Your reponame
          reponame: https://github.com/shenshuai89/shenshuai89.github.io
          # Your Github token
          token: ${{ secrets.ACCESS_TOKEN }}
          # Your git commit email
          gitemail: shenshuai89@qq.com
          # Your git commit name
          gitname: shenshuai89
          # Your git commit message
          gitmsg: update blog
          # Your custom domain
          cname: # optional, default is none
          # Move to this directory before deploy
          directory: docs/.vuepress/dist