# 定义 Workflow 的名字
name: 同步更新blog

# 定义 Workflow 的触发器；合并主分支后，执行打包
on:
  push:
    branches: [ "master" ]

# 定义 Workflow 的 job
jobs:
  build:
    name: deploy to shenshuai89.github.io
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install node
        uses: actions/setup-node@v3.0.0
        with:
          node-version: "16.17.0"
          registry-url: https://registry.npmjs.org
      - name: 全局安装依赖
        run: npm install
      - name: build打包构建
        run: npm run build
      # - name: Deploy to Server
      #   uses: JamesIves/github-pages-deploy-action@releases/v3
      #   with:
      #     ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      #     REPOSITORY_NAME: shenshuai89/shenshuai89.github.io
      #     BRANCH: master
      #     FOLDER: docs/.vuepress/dist
      # - name: Deploy Github Pages
      #   # uses: avinal/github-pages-deploy-action@7702e2ad1f82097323b08b428c8f57cb21dd965b
      #   uses: avinal/github-pages-deploy-action@v0.9
      #   with:
      #     # GitHub access token with Repo Access
      #     GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      #     # java(for JavaDoc), python(For Python Site/Documentation Generators)
      #     LANGUAGE: 
      #     # make command to generate html
      #     MAKE_COMMAND: bash deploy.sh
      #     # Deploy pages to which branch
      #     PAGES_BRANCH: https://github.com/shenshuai89/shenshuai89.github.io
      #     # Generate Site from which branch
      #     BUILD_FROM: # default is master
      #     # folder in which generated files are stored
      #     DOCS_FOLDER: docs/.vuepress/dist
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.2
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          REPOSITORY_NAME: shenshuai89/shenshuai89.github.io
          BRANCH: master
          FOLDER: docs/.vuepress/dist